### ISSUE TITLE
AccessDeniedException when searching genes by GO term as an anonymous user

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#1057]
![image](https://github.com/PavlidisLab/Gemma/assets/1318477/222a6666-1df0-4bf5-8004-c05ddadcb7dd)

**Comment by ppavlidis** [comment]
That is pulling up a gene group that was defined by one of our devs as a test. I deleted it. In fact, since we no longer support user-created gene groups we should probably delete all of them. 

But that's not the actual issue, there is a bug here, private gene groups shouldn't get that far in the search process and should instead yield an empty results.

Minor point: There is no GO:001 so nobody would search for that.  GO IDs are seven digits following `GO:`. The best match happened to be a private gene set.

**Comment by arteymix** [comment]
They are supposed to be filtered by acl, not cause an exception. This could be a problem for other entities, so I'll review the code.
