### ISSUE TITLE
Add an endpoint to retrieve all the DE results for a given gene 

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#1111]
We already have an endpoint that retrieve all the expression levels for a given gene. Having a similar endpoint for analysis results would be very useful as well.

- [x] allow for filtering and searching of experiments with the usual parameters for datasets
- [x] honor ACLs and troubled datasets/platforms
- [ ] add a tabular representation

**Comment by ppavlidis** [comment]
To be more specific, we mean without any filtering for "significance" etc. This would allow us to show things like the distribution of values for a gene, and give stats like how many times the gene was DE at some threshold, which is a diagnostic (cf: DEPrior).

We have service methods to do this (GeneDifferentialExpressionService) but lightweight versions might be needed that simply return the raw DE stats (namely FC and Q/PValues) for a gene _without_ also fetching experiment information. Those methods are designed for pulling out the top 50 or something, but we're talking about what could be 10k values.

Of course, pretty quickly it becomes interesting to stratify by information that is coming from the experiment (platform, tissue etc), but that could be done at the query level, rather than part of the data that is fetched.

**Comment by arteymix** [comment]
I'll exclude corrected P-values which only make sense when compared against other genes in a given result set.

**Comment by ppavlidis** [comment]
We'll want the q-values (which we inaccurately refer to internally as corrected pvalues in some places) as well as the p-values. The q-values might be more useful in the context of the use case, if we have to choose just one of the two for performance reasons.

**Comment by arteymix** [comment]
I'm thinking of just correcting P-values on the fly based on the retrieved raw P-values.

Implementation is completed, I'm testing it now.

**Comment by ppavlidis** [comment]
That won't work since FDRs are estimated across all genes. The FDR across studies is not computable in a simple way and would have a different interpretation.
