### ISSUE TITLE
User/Password flags (-u -p) in GemmaCLI no longer recognized for blackList command

### ISSUE THREAD

**Issue by nzllim** [PavlidisLab/Gemma#125]
Refer case: https://github.com/PavlidisLab/GemmaCuration/issues/11#issuecomment-765813751

This is a regression bug. -u and -p should be recognized by GemmaCLI in almost all operations, but is not happening in this instance.

**Comment by arteymix** [comment]
This is odd because the processing of username and password options is centralized in `AbstractCLI` and the logs suggests that these options are effectively being passed to the command. Also, the options are working for other commands.

I suspect that the options are defined twice because BlacklistCli explicitly call addUsernameAndPassword (once there and once in the superclass).

**Comment by sanjarogic** [comment]
@arteymix I am not sure I understand what's the solution for this bug? Do you still need to fix something or you are suggesting to run this command differently?
