### ISSUE TITLE
Mean Variance Plot not generated 

### ISSUE THREAD

**Issue by AlexAdrian-Hamazaki** [PavlidisLab/Gemma#138]
As discussed during our Friday curator meeting, the mean variance plot is not being automatically generated.

In order to generate the graph, we can re-process the diagnostics in the admin and curation tab of GEMMA.

**Comment by ppavlidis** [comment]
It should be getting generated whenever makeProcessedData (or the underlying PreprocessorService.process methods)  is used, and that includes addGEOData.

 It runs along with the other diagnostics (sample-sample correlation and PCA), so if the latter two are being generated, the MV plot also should.

If that MV plot generation specifically failed, there would be an error logged ("Could not compute mean-variance relation...").

If preprocessing fails entirely there will also be a error logged. 

However, there _was_ a bug I found in that it wouldn't do it if there was already one existing, but as I recall the problem was occurring when data was first being loaded (addGEOData) so still unclear if I've fixed the actual issue.
