### ISSUE TITLE
Multiplatform experiment with little probe overlap and random sample overlap

### ISSUE THREAD

**Issue by danjakco** [PavlidisLab/Gemma#143]
This experiment uses 3 Affymetrix platforms. When I ran a platform submission test to see if there is sufficient probe overlap between the platforms (for merging), and there is very little overlap (ex: 59/8789 probe biosequences). The samples are not split by experiment across the platforms either (i.e. it appears that the researchers ran the samples across all the different platforms randomly). So, it doesn't really make sense to split by platform. Would like to know how to proceed:

https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?shortName=GSE10238

**Comment by ppavlidis** [comment]
This looks like a case 2 https://wiki.pavlab.msl.ubc.ca/pages/viewpage.action?spaceKey=PavLab&title=Multiplatform+datasets+in+Gemma

It has to be loaded *with* auto sample matching, or if that was already done, the matching has to be confirmed or fixed via https://gemma.msl.ubc.ca/expressionExperiment/editExpressionExperiment.html?id=16242 (available through "more edit options" on the front page tab for the EE)

**Comment by ppavlidis** [comment]
If the wiki isn't clear about how to recognize these cases and how to handle them, please update it, but the documentation has been expanded and clarified several times, it's pretty detailed.

Note that the default when loading data is to have sample matching across platforms *on* and you have to disable it with the -nomatch option or whatever it is. 

I have recently mentioned that having it off might be a better default, because "case 1" is becoming more common than case 2, and definitely RNA-seq studies don't seem to be case 2 often if ever, and doing matching screws things up in that case. Either way, when loading multiplatform experiments you *have* to pay attention and ideally know which case it is before you load it.

Case 2 is primarily found for these kinds of multi-part old Affymetrix arrays.

**Comment by danjakco** [comment]
Great thank you Paul, I am going to add a bit of clarification to the wiki. Thanks for the clarification.
