### ISSUE TITLE
Differentially expressed probes visualizer is using the wrong set of FactorValues for subset analyses

### ISSUE THREAD

**Issue by nzllim** [PavlidisLab/Gemma#144]
Link: https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=14307

This problem occurs for the first subset:
![image](https://user-images.githubusercontent.com/6352377/110709644-66462680-81b1-11eb-9d43-579060f75ffb.png)

In reality it should be showing the genotype FVs for "Experiment 1" subset, i.e. Mouse Runx1, Runx2 and Runx3 over-expression. This is not the case - instead it is showing the FVs for the subsetting ExperimentalFactor (collection of materials), which is wrong. Also, it is showing the Human Runx1 over-expression, which is not involved in this subset.

Thankfully, the downloadable files (i.e. DE matrix) appears correct, so this is purely a visualization bug.

**Comment by ppavlidis** [comment]
Is this an issue for any other data set? Because the problem seems to be that the data for the subsets is messed up somehow.

The two subsets have overlapping samples (which should be a problem for the DEA, but I don't know what happened). I suggest we redo the analysis and see if that clears it up.

![image](https://user-images.githubusercontent.com/206415/126412581-1475f55e-2a51-4f9f-ba07-a2bdb9561b4b.png)

**Comment by ppavlidis** [comment]
This was some glitch with the data. There is a minor issue in still showing the subset factor, but it is correctly shown.
