### ISSUE TITLE
Spaces in experiment short names break API endpoints

### ISSUE THREAD

**Issue by jsicherman** [PavlidisLab/Gemma#145]
There is one experiment whose short name includes a space (McLean Hippocampus, ID 670). For RESTful API endpoints that use the experiment short name as the identifier in the middle of the path, a 404 is raised. For example,

https://gemma.msl.ubc.ca/rest/v2/datasets/McLean%20Hippocampus works (short name is terminal)
https://gemma.msl.ubc.ca/rest/v2/datasets/McLean%20Hippocampus/platforms fails (short name is non-terminal)

Seems like most short names enforce no spaces so this fix is probably as simple as changing "McLean Hippocampus" to "mclean-hippocampus".

**Comment by arteymix** [comment]
I'm going to simplify the @PathParam that accept pretty much anything.

The issue we have is that we initially set up catch-all routes to produce 404 errors, and those get precedence for handling requests. That's why we always have to specify regular expressions for matching path parameter.

https://github.com/PavlidisLab/Gemma/blob/ba96a12849653cf11e1b9b3cd32b358d4e53490e/gemma-web/src/main/java/ubic/gemma/web/services/rest/util/WebService.java#L30

The solution is to replace those routes with a [NotFoundException](https://docs.oracle.com/javaee/7/api/javax/ws/rs/NotFoundException.html) mapper. That's the native mechanism with jax-rs to treat unmapped requests.
