### ISSUE TITLE
Platform datasets endpoint offset not working

### ISSUE THREAD

**Issue by yavyx** [PavlidisLab/Gemma#164]
Example query:
https://gemma.msl.ubc.ca/rest/v2/platforms/GPL1355/datasets/?offset=5&limit=20

The offset is not working, it always returns the same datasets regardless of its value.

**Comment by arteymix** [comment]
I'll look into this right now! Wish me luck :)

**Comment by arteymix** [comment]
The query is containing duplicate results because it uses a regular SQL query (in HQL) and the model (i.e. the ArrayDesign) itself is not retrieved, but rather specific columns. This results in the ArrayDesign appearing as many time as necessary to match the joined tables.

To fix this, we need to fetch an ArrayDesign instead of a bunch of columns (i.e. `Object[]`) and fill the gaps that the extra columns provide (i.e. is the platform merged, troubled, etc.).

**Comment by arteymix** [comment]
I wish we designed the DAO in a simpler fashion, with one explicit query per method, even if that would lead to some code duplication. It's confusing to have dozens of constants and methods referenced when building SQL queries. Anyway, this should be fixed in a few minutes.

**Comment by arteymix** [comment]
Just a quick divergence, I've splitted the `BaseVoEnabledService` and `BaseVoEnabledDao` to isolate the `loadValueObjectsPreFilter`routine which is the culprit for this bug. The current code will be exactly the same, but that will allow us to make a the querying, filtering, ordering, etc. in a generic manner and address systematically the problem of offset. Other endpoints are affected by this because they use the same scheme for querying the database.

**Comment by arteymix** [comment]
Okay, it's working now :)  I've also added an interface for producing `Slice<T>` with `loadValueObjectsPreFilter` (see #180) and a new `PaginatedResponseDataObject` which augments `ResponseDataObject` with offset, limit, sorting scheme and total elements. This is working for datasets and platforms, and eventually should be extended to all other endpoints.

Key takeaways:

 - it's impossible to use `count(*)` and selecting entities in the same query unless a `group by` clause is used (but then it becomes useless)
 - fetch join don't work in counting queries, only if the entity is retrieved

**Comment by yavyx** [comment]
This endpoint still has unwanted behavior, it is now returning one dataset, times the limit. The offset is not working either.

Some examples:
https://gemma.msl.ubc.ca/rest/v2/platforms/GPL1355/datasets/?offset=0&limit=20
https://gemma.msl.ubc.ca/rest/v2/platforms/GPL1355/datasets/?offset=1&limit=20
https://gemma.msl.ubc.ca/rest/v2/platforms/GPL570/datasets/?offset=5&limit=20
https://gemma.msl.ubc.ca/rest/v2/platforms/GPL570/datasets/?offset=0&limit=10

**Comment by arteymix** [comment]
This is not yet merged in the master branch. It will be available in the next release.

In the meantime, try https://dev.gemma.msl.ubc.ca/rest/v2/platforms/GPL1355/datasets/?offset=1&limit=20
