### ISSUE TITLE
Display a reason when diagnostic plots haven't been computed

### ISSUE THREAD

**Issue by sanjarogic** [PavlidisLab/Gemma#168]
It used to be that only mean-variance plot would not load after the RNAseq processing, but the latest batch of samples also doesn't have the PCA+Factors plot. The mean-variance one shows up after running the manual diagnostics, but PCA+Factors plot still fails to generate.

**Comment by ppavlidis** [comment]
I will need some log files to see what is happening, and/or an example of a data set with the problem

**Comment by sanjarogic** [comment]
Some examples: [GSE152400](https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=19040), [GSE156170](https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=19038), [GSE155691](https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=19042), [GSE161394](https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=19044), [GSE124239](https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=19048)

**Comment by ppavlidis** [comment]
None have an experimental design == no factors, so the PCA-factor plot will not be generated. The situation may simply be that the RNA-seq pipeline is ahead of the curators.

There is possibly (?) still an issue with the MV plot not being generated right away, but that also requires the experimental design to be done properly (the values displayed are after regressing out the experimental design). In other words, it would have to be regenerated after curation anyway. 

It would be nice if the page indicated the reason it isn't shown, but it's a low priority because the data won't be made public before curation is finished, so it wouldn't be shown except for studies that will never have an experimental design (which is rare)

**Comment by sanjarogic** [comment]
oh ok, that makes sense. I haven't seen this before, which means that all the previous experiments that I was running through the pipeline were already curated.  The MV plots are usually never displayed after the data is loaded, so that's probably unrelated to curation status.

**Comment by ppavlidis** [comment]
Yes, it would help to see the logs for what happens at the end of the pipeline w.r.t. why the MV plots aren't generated even when there is an experimental design.  @arteymix 

Looking at the code, there are two main error states that could occur:

1. Postprocessing isn't done at all, which would be weird since when we add RNA-seq data, we are presumably always adding the "preferred" quantitation (log2cpm in this case) type which is the only requirement. The logs should normally record "Postprocessing preferred data"
2. There is an exception thrown during MV processing, in which case the exception should be logged (with "Could not compute mean-variance relation").  Subsequent postprocessing steps will carry on, the exception is caught.

**Comment by sanjarogic** [comment]
Some examples: [GSE152400](https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=19040), [GSE156170](https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=19038), [GSE155691](https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=19042), [GSE161394](https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=19044), [GSE124239](https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=19048)

**Comment by arteymix** [comment]
This is fixed!

This was caused by JFreeChart unexpectedly initializing Swing when $DISPLAY is set. This can happen if you use X11 forwarding, but then close your SSH session and leave the process alive via tmux. See #492
