### ISSUE TITLE
Multiple "Reoccurence" (?) of Similar Quantitation Types in RNA-Seq Experiments

### ISSUE THREAD

**Issue by nzllim** [PavlidisLab/Gemma#22]
Cases-In-Point:
http://www.chibi.ubc.ca/Gemma/expressionExperiment/showExpressionExperiment.html?id=10706
http://www.chibi.ubc.ca/Gemma/expressionExperiment/showExpressionExperiment.html?id=9591

A brief discussion with @ppavlidis suggests this to be a bug. It should be noted that luckily the repeating QT's are not the preferred QT.

**Comment by ppavlidis** [comment]
nzlim says that he thinks this happens when we load data repeatedly - we create a new QT each time, presuming an appropriate one doesn't exist. Instead we should check for an appropriate QT or else delete the old QTs when we make a new one.

**Comment by tesar-stepan** [comment]
The QTs should be already getting removed when the data is reloaded. I remember recently that some seemingly unrelated update in gemma broke a test because it ran the code that was handling the deletion and there was an obvious error in it, which leads me to believe that that code was never reached before. This should not be happening with new experiments, and current QTs will have to be checked for being orphaned and removed.
