### ISSUE TITLE
Dates are in the JSON representation are using UNIX epoch instead of ISO 8601

### ISSUE THREAD

**Issue by dima-v-v** [PavlidisLab/Gemma#301]

**Comment by arteymix** [comment]
This will require configuring the Jackson ObjectMapper.

**Comment by arteymix** [comment]
Changing this will break the [https://github.com/PavlidisLab/gemma.R] API which actually parses UNIX epoch.

In addition to this, we might want to adjust the way dates are compared in `ObjectFilter` to use ISO 8601 too. `Instant.parse` can handle this, but it does not work with date without time. Jackson has `StdDateFormat` which handle pretty much all the cases, but might be too permissive because it also accepts RFC1123.

**Comment by arteymix** [comment]
Reference from gemma.R: https://github.com/PavlidisLab/gemma.R/issues/18

**Comment by arteymix** [comment]
Feature was added in https://github.com/PavlidisLab/Gemma/commit/cb2d89b7dc0bdfbd78bcf1e21b934f4d23c62a77

**Comment by arteymix** [comment]
Two things to resolve now: configure `ObjectMapper` to emit ISO 8601 datetimes and see if we want to stick to Jackson's `StdDateFormat` for the parser implementation.

**Comment by arteymix** [comment]
Fixed in 643a6b982cf9a5d3aa16dce57090a196b1013bb4

We now produce and consume ISO 8601 dates with Jackson's `StdDateFormat`.
