### ISSUE TITLE
Expose raw-er "preferred quantitation type" data

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#362]
For users that don't want to rely on our outlier removal, batch correction and normalization approach, we should provide an endpoint (and via the GUI, might as well) to access the data in a more raw state, prior to the application of these steps.

I believe this should be reasonably straightforward via `ProcessedExpressionDataVectorDao.getPreferredDataVectors()`

- [ ] add a getDatasetRawExpression endpoint to the public API with the same size gnature as getDatasetExpression
- [ ] devise an HQL query to retrieve the preferred raw expression vectors
- [ ] recover gene metadata from the GENE2CS table using the result set query
- [ ] adapt the processed EV endpoint to use the same gene metadata query (for the 1.5.0)

**Comment by arteymix** [comment]
Upon doing some work with using the GENE2CS table to map data vector to gene annotations, I also took the liberty to map raw data vectors as well. I'll ship all those features together.

**Comment by arteymix** [comment]
I'll add a `raw` argument to the `getDatasetExpression` endpoint. Relevant endpoint is here:

https://github.com/PavlidisLab/Gemma/blob/development/gemma-web/src/main/java/ubic/gemma/web/services/rest/DatasetsWebService.java#L305-L327

**Comment by ppavlidis** [comment]
Thanks. It will be important to clearly document exactly the state of the data (what has and hasn't been done) for users. Another step in processing is removal of low-intensity spots for ratiometric microarrays, what we call missing value imputation. The method I mentioned should yield data prior to that step as well?

**Comment by arteymix** [comment]
@ppavlidis How do we distinguish between different set of processed or raw expression vectors? 

Here's my understanding of the important pieces:

 - bioAssayDimension: basically keep BioAssay in order since we encode expression level for a full gene row
 - designElement: what probe expression levels are being encoded
 - quantitationType: what distinguishes different possible representation of gene expression
 - data: an encoded data vector

Looking up the models, I noticed that they seem to be using different quantitation type, which makes sense, but I don't see how that prevents an EE from having two different sets of FPKMs resulting in duplicated probes in the expression matrix. Do we simply disallow that?

I also see that we have a notion of preferred QT type. That makes plenty of sense if there are multiple raw or processed vectors to pick a single one for download or analyses purposes. Should the raw download be simply a download of preferred raw vectors?

For the API, it might also make sense to specify a `quantitationType` parameter that allow one to pick whatever QT type is relevant (assuming that the QT type separates perfectly the possible representations, unlike the FPKM example above).

**Comment by arteymix** [comment]
I don't want to make this more complicated than necessary, though. It can simply be a processed or raw binary choice, and we do the picking internally. I just want to make sure I understand well what that would implicate.

**Comment by arteymix** [comment]
I could also use that to speed up the GENE2CS loading by selecting more carefully the relevant data vectors, I'm picking all those related to an EE presently which certainly include non-preferred/irrelevant ones.

**Comment by ppavlidis** [comment]
As mentioned in the issue `ProcessedExpressionDataVectorDao.getPreferredDataVectors()` should be providing the desired data. As you say, we define a "preferred" quantitation type that represents the expression levels to distinguish it from other measures. This is most often relevant to two-color microarrays which have things like "green background", "red background" as well as "green signal", "red signal" and "log ratios of G/R" -- the last one is what we want.

**Comment by arteymix** [comment]
Just to clarify: wouldn't the raw-er EVs be provided by `RawExpressionDataVectorDao` instead?

**Comment by ppavlidis** [comment]
They are RawExpressionDataVectors, I was just going by our code which retrieves them prior to the other processing and the method for doing that is in the ProcessedExpressionDataVectorDao (see line 858). I agree that perhaps that method should logically be in the RawExpressionDataVectorDao, but that's a detail.

**Comment by arteymix** [comment]
Raw expression levels are now exposed under `/datasets/{datasetId}/data/raw` endpoint with 264ce1cc94cdcd593bdd776870092b9ee865d8f1.
