### ISSUE TITLE
Potential issue with NCBI gene annotation files

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#376]
My last attempt to update the gene information didn't find any changes to be made.

This seems exceedingly unlikely, so I believe must have changed in the files we are using.

One way to investigate this: the tests should be updated to use the newest files. In particular NCBIGeneLoadingTest; there is a README in test/resources/data/loader/genome/gene that explains how to generate the files for testing, though the full downloads are now in /cosmos/scratch/curator-scratch/databases/ncbi.

If those revised tests fail in non-trivial ways (some details of the tests will have changed), we should be able to more easily figure out what the issue is.

But maybe before that we should compare the small test files we have to the format of the ones we just downloaded to see if there's an obvious difference.

**Comment by ppavlidis** [comment]
Actually the test files are not as well documented as I'd have liked, regenerating them isn't going to be so easy/fun so I am starting with just inspecting the input files. I am also referring to the NCBI [README](ftp://ftp.ncbi.nlm.nih.gov/gene/DATA/README) 

Checking the identify and location of columns:
* gene2ensembl: we only use two fields and these are in the right place in the latest files and in the expected format
* gene_history: confirmed all columns are as expected
* gene2accession: confirmed all columns are as expected
* gene_info: also confirmed our parser is handling the file correctly.

Fortunately it seems nothing has grossly changed in the file formats. There may be some issue with the content of the columns, though I haven't spotted anything.

**Comment by arteymix** [comment]
The changes to the NCBI gene loader has been reverted. There had to be something broken about the waiting condition between the various threads.

The other issue that was encountered down the line appears to be a change in the lazy loading of gene product accessions. Normally, this should work, but it seems that the gene product originated from a different session than what the persister is using since the whole persistOrUpdate operation runs in a single transaction.
