### ISSUE TITLE
Match result sets associated to EE subsets for a given dataset

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#457]
We need to include `experimentAnalyzed.sourceExperiment` in the dataset query only if the `experimentAnalyzed` is an EE subset.

@oganm This explains why /rest/v2/resultSets?datasets=442 and /rest/v2/datasets/442/analyses/differential don't produce the same set of result sets.

**Comment by arteymix** [comment]
I tried to fiddle with the criteria query to see how easy it would be to include them, but was unsuccessful. I'll schedule this for the next release.

**Comment by arteymix** [comment]
It might be easier to work the other way around and expand the set of BioAssays used for filtering analyses with all the subsets.

**Comment by ppavlidis** [comment]
Note that 442 is weird because it was not analyzed correctly - it has an "overall" as well as a subset analysis. I've asked curators to look at it. A more straightforward one is 23826

https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=23826

Certainly https://dev.gemma.msl.ubc.ca/rest/v2/resultSets?datasets=23826 should return those DEAs. 

What isn't too clear (to me) is whether this is important to the R package right now? Because it should be fixed but if it's not important to the API we can do it for a future release.

**Comment by arteymix** [comment]
The other question this raises is whether exposing `bioAssaySetId` is appropriate in `DifferentialExpressionAnalysisValueObject` as that might refer to a subset for which there is no method of querying.

I'm suggesting that we should always fill `sourceExperiment` with the `ExpressionExperimentSubSet.sourceExperiment` (for subsets) or `ExpressionExperiment.id` (for whole-experiment analysis). There's always the `isSubset` and `subsetFactor` attributes to get the full picture.

**Comment by arteymix** [comment]
The R package favours `sourceExperiment` when available, so there's no harm in hiding `bioAssaySetId`:

https://github.com/PavlidisLab/gemma.R/blob/65866c85d1593adf30dfe8d07032dcb88cd877cc/R/processors.R#L221

**Comment by arteymix** [comment]
Ok, this is completely fixed now. I had to adjust the ACL filtering to also include ExpressionExperimentSubSet in 58268313e4c47bcee296f995f0b2aff6229bcbbb and ensure that subsetFactorValue is always initialized.
