### ISSUE TITLE
Only expose GEEQ quality score and hide manual override

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#597]
The manual override should be hidden from the  user be transparently exposed as a score.

Use an alias to map the quality score to a filtering property and perform the automatic translation for the backend in DatasetArgService.

**Comment by arteymix** [comment]
We already expose suitability scores, so I'll also include them in the filterable properties. We should make a decision later as to whether or not we want to make it visible only for internal use.

**Comment by arteymix** [comment]
I've added a `case(...)` statement in the filtering query select clause, allowing us to filter by quality and suitability scores, and will be mapping this to the filterable properties. It would be interesting to start considering using expression for the `Filter` and `Sort` mechanism instead of properties.

**Comment by arteymix** [comment]
I've also added index on the corresponding columns as to fully resolve #562.

**Comment by ppavlidis** [comment]
Yes, suitability scores should only be exposed to administrators. 

Just for the record on the history: the original GEEQ score did not have these two components. However, we decided some of the GEEQ features weren't about quality (the purpose of GEEQ) but about how useful the data is within Gemma. We therefore separated them out.

It was considered whether we should just discard those features entirely, but there was little harm in keeping them and we could experiment with whether they are useful. But we decided users of the system wouldn't care about how useful the data is from our point of view (that's up to them). So we only show that score to curators. I wouldn't say it has proved to be very useful.

On the other hand, the quality score has been more useful as well as something we've experimented with as a way to weight experiments in downstream analyses. There may be some benefit, but the scores (and how they are combined) aren't "trained" on some objective criterion of "quality" (that would be difficult to define in a general way).  It is based on experience so that the scores correlate with some gestalt of curator judgement of how good a data set it. I'd consider it a rough human-interpretable indicator of some common issues that we observe, and useful for bringing them to attention of users.

So quality scores have some value in helping guide subjective decisions about whether to use a data set, but their value as computational weights (etc.) is not established (IMO).

As for the manual override: this feature should be deprecated. I was never in favour of it and it never gets used, and using it could crate issues with injecting more subjectivity into the GEEQ score.

**Comment by arteymix** [comment]
I agree that it should be deprecated, but for now we need to honour the current system since it's already being used for producing the GEEQ VO.

I'll add deprecated annotations and review current usages and schedule removal for the the 0.31 release.

**Comment by arteymix** [comment]
The solution is pretty neat: https://github.com/PavlidisLab/Gemma/commit/3fb0368fa865a81c79640e70afe28a279a980d5a#diff-6d0a778767ce3d1873048aeabbdadddd64a1827becf2c8fc3c86ebc026cf3627

I registered properties that use a `(case when geeq.manualQualityOverride = true then geeq.manualQualityScore else geeq.detectedQualityScore end)` as property name.
