### ISSUE TITLE
Ontology inference does not work with part of relations

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#603]
It seems that the terms we currently use in baseCode to identify "part of" relation to expand the scope of our inference is not used anymore:

 - http://www.obofoundry.org/ro/ro.owl#proper_part_of
 - http://www.obofoundry.org/ro/ro.owl#has_proper_part

This has to be addressed in baseCode and would be to include in the next patch release. I'll try to compile a list of terms through which we want to propagate inference.

**Comment by ppavlidis** [comment]
So this was due to a change in the ontologies? 🤦 

Wouldn't be the first time, won't be the last.

**Comment by arteymix** [comment]
Very likely so. The new term that is being used for `part of` is http://purl.obolibrary.org/obo/BFO_0000050. I think we use the same one for RDP's GO ontologies.


 Ideally, the terms we want to propagate through should be ontology-specific and configurable so we don't need code changes to address upstream changes.

**Comment by arteymix** [comment]
The reverse relation is `has part` http://purl.obolibrary.org/obo/BFO_000005.

**Comment by arteymix** [comment]
That should do the trick! 

https://github.com/PavlidisLab/baseCode/pull/29/commits/4360045938760dc28efda989ef958bd0dbec0b2c

**Comment by arteymix** [comment]
We have working tests for the previous term, so I suspect the fixtures are decades old.

**Comment by ppavlidis** [comment]
Just want to clarify for future readers that we're talking about relationships among ontology concepts (which I usually just call terms) and which ones we follow when doing inference. Those relationships are themselves represented by ontology concepts but they're not concepts "in the ontology" like "brain" is, for our purposes. 

Our rules were that a term is a child of another term (the 'parent') if it has a part_of or is_a relationship with it. (this has been the status quo for about 20 years). There are other types of relationships but they don't fit the sort of "subclass-ish" semantics that we want to use for inference (hippocampus is part of the brain, tyrosine kinases are kinases, but X 'regulates' Y is out of scope for example)

Ideally the relationships we propagate *wouldn't* be ontology specific; we just need to add another term that we consider useful for inference, proper_part_of, which is from 'child' to 'parent'.

has_part and has_proper part are presumably relations in the other direction (form parent to child); we don't want to propagate through those as well because we'll have loops?

**Comment by arteymix** [comment]
Finally fixed in 0af462dc4c11ad10e306489af4eabad3a230046b! baseCode now does proper inference for `part of` and `proper part of` for both ancestors and descendants of a term. The commit is a bit bigger than expected because I also took the opportunity to switch GeneOntologyService to baseCode's OntologyService API, fixing in the process a few edge cases for GO terms.
