### ISSUE TITLE
ProcessedExpressionDataVector fields (rankByMax, rankByMean) are not populated for experiments loaded after Summer 2018

### ISSUE THREAD

**Issue by nzllim** [PavlidisLab/Gemma#77]
As title, the fields for rankByMax and rankByMean for PEDV objects are left as Nulls for experiments loaded into Gemma after Summer 2018.

What the problem is not:
The get/set methods work fine for experiments prior to the time period.

What the problem could be:
The calculation step during the processing of expression data has been skipped/removed, or the information was not committed to the database.

Case-In-Point:
https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=14287

**Comment by ppavlidis** [comment]
I've determined that this is not a bug, just a few cases where the computation seems to have glitched for one reason or another; it should just need to be redone. It does not affect all experiments since summer 2018 - only about 30 since June. And most of the cases I've examined cannot have ranks computed because we lack intensity data (e.g. some two-color data sets).
