### ISSUE TITLE
Accept submission of batch information for single lanes

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#89]
Experiments that are performed on a single lane carry useful information that should be displayed the same as those that don't incur batch effects.

Here are some examples of datasets with that property:

 - GSE127446
 - GSE57694
 - GSE54729.1
 - GSE52202
 - GSE119883
 - GSE80745

**Comment by arteymix** [comment]
This is a much bigger issue than I anticipated that affects a substantial fraction of the experiments marked as unusable. 

There are even cases of experiments with partial lane information (which can still be useful) and experiments with non-standard lane information (which are fine to reject).

**Comment by arteymix** [comment]
About 10% of the curated RNA-Seq datasets are performed on a single lane.

**Comment by ppavlidis** [comment]
Thanks. We're meant to record a BatchInformationFetchingEvent in all cases where we got valid batch information regardless of whether there was >1 batch, which means we can infer the situation you describe easily. This is working correctly for microarray data sets, but the event isn't being added for the RNA-seq case, will be fixed.

We don't store a batch factor because we require factors to have more than one level.

**Comment by arteymix** [comment]
Is there any way I can query whether correct batch information have been submitted via the web API? So far, I've been relying on the existence of a batch factor.

**Comment by ppavlidis** [comment]
I don't think so but we can add such an endpoint
